### ISSUE TITLE
coverage_basis no longer returns a Collection<string>

### ISSUE THREAD

**Issue by ewahner** [eligible/eligible-CSharp#14]
The "coverage_basis" property no longer returns a simple collection strings.  It now returns a collection of objects.  A new class needs to be created to handle this and the Service class should change to accommodate.

I suggest creating a new class called CoverageBasis and then change the Service class to return a Collection or List of CoverageBasis objects.

**CoverageBasis**

    `public class CoverageBasis
    {
        [JsonProperty("_")] 
        [JsonIgnore]
        public string NullValue { get; set; }

        [JsonProperty("comments")]
        public List<string> Comments { get; set; }
    }`
**Service**

    `public class Service
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("type_label")]
        public string TypeLabel { get; set; }

        [JsonProperty("coverage_status")]
        public string CoverageStatus { get; set; }

        [JsonProperty("coverage_status_label")]
        public string CoverageStatusLabel { get; set; }

        [JsonProperty("facility")]
        public FinancialFlowsList Facility { get; set; }

        [JsonProperty("coverage_basis")]
        public Collection<CoverageBasis> CoverageBasis { get; set; }

        [JsonProperty("financial_flowsList")]
        public FinancialFlowsList FinancialFlowsList { get; set; }

        [JsonProperty("non_covered")]
        public Collection<NonCovered> NonCovered { get; set; }

        [JsonProperty("benefit_details")]
        public BenefitDetails BenefitDetails { get; set; }

        [JsonProperty("financials")]
        public Financials Financials { get; set; }

        [JsonProperty("visits")]
        public Financial Visits { get; set; }

        [JsonProperty("additional_insurance_policies")]
        public Collection<AdditionalInsurancePolicy> AdditionalInsurancePolicies { get; set; }
`

**Comment by balu-eligible** [comment]
Thank you Ewahner for reporting the issue,

We are woking on it. We will update you once done. 

Regards,
Balu

**Comment by balu-eligible** [comment]
We have done with the changes. Eligible.Net 1.0.3 has the changes. 

Thanks,
Balu.
