### ISSUE TITLE
Invalid object when parsing PreexistingCondition

### ISSUE THREAD

**Issue by ewahner** [eligible/eligible-CSharp#18]
The PreexistingCondition in the Model.Coverage.PreexistingCondition has a property called "WaitingPeriod" or "waiting_period" in the JSON.  This is stated to be a Collection of string, however it is not.  Here is a sample json node of what actually comes back:

`"pre_existing_condition": {
        "waiting_period": [
          {
            "": {
              "date": null,
              "comments": [
                "PRE-EXISTING IS WAIVED"
              ]
            }
          }
        ]
      }`

So when the object is Deserialized it fails.

**Comment by ewahner** [comment]
Just as an FYI to fix this...I did the following.  Perhaps it will work for you as well:

I created 2 new classes...one called WaitingPeriod and another just called Period and then modified the PreexistingCondition class to contain a collection of waitingperiod objects

`    public class PreexistingCondition
    {
        [JsonProperty("waiting_period")]
        public Collection<WaitingPeriod> WaitingPeriod { get; set; }
    }

    public class Period
    {
        [JsonProperty("date")]
        public DateTime? Date { get; set; }
        [JsonProperty("comments")]
        public string[] Comments { get; set; }
    }

    public class WaitingPeriod
    {
        [JsonProperty(" ")]
        public Period Period { get; set; }
    }
`

**Comment by balu-eligible** [comment]
Hi Eric Wahner,

Thank you for reporting the issue. 
We are working on it. We will notify you once corrected. Thank you!

Regards,
Balu.

**Comment by balu-eligible** [comment]
Hi Eric, 

We fixed this issue. Please update to the latest version of library.

Please let us know if you have any issues. Thank you!

Regards,
Balu.
