### ISSUE TITLE
Improper parsing as success

### ISSUE THREAD

**Issue by avi-berkowitz-zocdoc** [eligible/eligible-CSharp#42]
When calling Coverage, the TryParseJson function that converts the response into a success or failure object improperly parses the response as successful under certain circumstances.  Specifically, if multiple_stc is set to true in the request, the response object contains a "services" key regardless of whether or not the request was successful.  The TryParseJson function determines if the response is successful or not by counting the number of non-null values for the expected keys.  If more than half of the expected keys are not null, it's considered successful:

https://github.com/eligible/eligible-CSharp/blob/master/Eligible.NET/src/EligibleService.Common/RequestProcess.cs#L125

I would propose that this is a brittle approach, as evidenced by this particular issue.  I would recommend leveraging HTTP response codes (500, specifically) to more explicitly differentiate between successful and failure responses.

Separately, I could see a situation whereby, with multiple_stc set to true, some of the backend calls to the insurance carrier succeed and some fail.  In this situation, it may make more sense to append the error key to individual services in the array, and add support for that key in the `CoverageResponse` type.

**Comment by balu-eligible** [comment]
Hi Berkowitz,

Thanks for reporting the issue. We started working on this and will get back to you soon!

Regards,
Balu.
